import scrapy


class ChargeItem(scrapy.Item):
    """An item for representing charge data."""

    name = scrapy.Field()
    sex = scrapy.Field()
    dob = scrapy.Field()
    height = scrapy.Field()
    weight = scrapy.Field()
    hair_color = scrapy.Field()
    hair_length = scrapy.Field()
    eye_color = scrapy.Field()
    complexion = scrapy.Field()
    booking_no = scrapy.Field()
    image_id = scrapy.Field()
    perm_id = scrapy.Field()
    person_id = scrapy.Field()
    police_county_id = scrapy.Field()
    race = scrapy.Field()
    ethnicity = scrapy.Field()
    marital_status = scrapy.Field()
    citizen = scrapy.Field()
    country_of_birth = scrapy.Field()
    curr_loc = scrapy.Field()
    county = scrapy.Field()
    commit_date = scrapy.Field()
    proj_release_date = scrapy.Field()
    bond_type = scrapy.Field()
    bond_status = scrapy.Field()
    posted_by = scrapy.Field()
    post_date = scrapy.Field()
    bond_total = scrapy.Field()
    charges = scrapy.Field()
    case_no = scrapy.Field()
    offense_date = scrapy.Field()
    code = scrapy.Field()
    description = scrapy.Field()
    grade = scrapy.Field()
    degree = scrapy.Field()
    scrape_time = scrapy.Field()
